language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-interaction --no-progress --prefer-dist

script:
  # Tests
  - composer test

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - stage: Quality Assurance
      php: 7.4
      name: "Coding standard"
      script:
        - composer cs
    -
      name: "PHPStan"
      php: 7.4
      script:
        - composer phpstan

    - stage: Test Coverage
      php: 7.4
      if: branch = master AND type = push
      script:
        - composer coverage
      after_script:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
        - php php-coveralls.phar --verbose --config .coveralls.yml

  allow_failures:
    - stage: Test Coverage

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
