language: php
php:
  - 7.2

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

jobs:
  include:
    - stage: Quality Assurance
      name: "Coding standard"
      script:
        - composer cs
    -
      name: "PHPStan"
      script:
        - composer phpstan

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
